export const LINK_ADD_REQUEST = 'LINK_ADD_REQUEST';
export const LINK_ADD_SUCCESS = 'LINK_ADD_SUCCESS';
export const LINK_ADD_FAIL = 'LINK_ADD_FAIL';

export const LINK_LIST_REQUEST = 'LINK_LIST_REQUEST';
export const LINK_LIST_SUCCESS = 'LINK_LIST_SUCCESS';
export const LINK_LIST_FAIL = 'LINK_LIST_FAIL';
